// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XYV68aQp6Pj32SOK7DDUnILkzDZjxS0',
    appId: '1:391296097434:web:c232a49503878995e45323',
    messagingSenderId: '391296097434',
    projectId: 'shetrack-67b0d',
    authDomain: 'shetrack-67b0d.firebaseapp.com',
    storageBucket: 'shetrack-67b0d.firebasestorage.app',
    measurementId: 'G-19PYPNG2SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHvNKaQ2gbQp12U7l60tiuAPCTQrc2vA',
    appId: '1:391296097434:android:3bbed1d7e0530b37e45323',
    messagingSenderId: '391296097434',
    projectId: 'shetrack-67b0d',
    storageBucket: 'shetrack-67b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84IWZTXf0EwUURSxVe8xaJPNzobfamck',
    appId: '1:391296097434:ios:535f79e62fb717b5e45323',
    messagingSenderId: '391296097434',
    projectId: 'shetrack-67b0d',
    storageBucket: 'shetrack-67b0d.firebasestorage.app',
    iosBundleId: 'com.example.shetrackv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84IWZTXf0EwUURSxVe8xaJPNzobfamck',
    appId: '1:391296097434:ios:535f79e62fb717b5e45323',
    messagingSenderId: '391296097434',
    projectId: 'shetrack-67b0d',
    storageBucket: 'shetrack-67b0d.firebasestorage.app',
    iosBundleId: 'com.example.shetrackv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5XYV68aQp6Pj32SOK7DDUnILkzDZjxS0',
    appId: '1:391296097434:web:e1155f75d9a3d873e45323',
    messagingSenderId: '391296097434',
    projectId: 'shetrack-67b0d',
    authDomain: 'shetrack-67b0d.firebaseapp.com',
    storageBucket: 'shetrack-67b0d.firebasestorage.app',
    measurementId: 'G-3J5MXBQ4YP',
  );
}
